"""feature_pipeline.py — generated by 01_data_preparation.ipynb.

Single source of truth for the feature-engineering transformation.
All fitted statistics live in artifacts/feature_artifacts.pkl; this module
only contains the transformation logic. Import from any notebook:

    from feature_pipeline import load_artifacts, engineer_features
    load_artifacts()
    X = engineer_features(raw_df)
"""
import pickle
import numpy as np
import pandas as pd
from pathlib import Path
from sklearn.preprocessing import LabelEncoder

_ART = None

def load_artifacts(path=None):
    global _ART
    if path is None:
        here = Path(__file__).resolve().parent
        path = here / 'artifacts' / 'feature_artifacts.pkl'
    with open(path, 'rb') as f:
        _ART = pickle.load(f)
    return _ART

def engineer_features(df_input, artifacts=None):
    art = artifacts if artifacts is not None else (_ART or load_artifacts())
    TRAIN_MEDIANS   = art['TRAIN_MEDIANS']
    TOP50           = art['TOP50']
    REGION_FAIL_MAP = art['REGION_FAIL_MAP']
    _global_fail    = art['global_fail']
    COMBINED_VOCAB  = art['COMBINED_VOCAB']

    df_out = df_input.copy()

    # Date
    df_out['date_recorded'] = pd.to_datetime(df_out['date_recorded'])
    df_out['year_recorded']  = df_out['date_recorded'].dt.year
    df_out['month_recorded'] = df_out['date_recorded'].dt.month
    df_out.drop(columns=['date_recorded'], inplace=True)

    # Drop columns
    drop_cols = ['id', 'recorded_by',
                 'wpt_name', 'subvillage', 'ward', 'scheme_name',
                 'payment_type', 'quantity_group', 'source_type',
                 'extraction_type', 'waterpoint_type_group']
    df_out.drop(columns=[c for c in drop_cols if c in df_out.columns], inplace=True)

    # Impossible zeros -> NaN
    for col in ['longitude','latitude','construction_year','population','gps_height','amount_tsh']:
        if col in df_out.columns:
            df_out[col] = df_out[col].replace(0, np.nan)

    # Impute numerics with train-only medians
    for c in df_out.select_dtypes(include='number').columns:
        if df_out[c].isnull().any():
            df_out[c] = df_out[c].fillna(TRAIN_MEDIANS.get(c, df_out[c].median()))

    # Derived features
    df_out['pump_age'] = (df_out['year_recorded'] - df_out['construction_year']).clip(lower=0)
    df_out['log_population'] = np.log1p(df_out['population'])
    df_out['log_amount_tsh'] = np.log1p(df_out['amount_tsh'])

    if 'region' in df_out.columns:
        df_out['region_fail_rate'] = df_out['region'].map(REGION_FAIL_MAP).fillna(_global_fail)

    if 'quantity' in df_out.columns and 'payment' in df_out.columns:
        df_out['qty_pay_combo'] = (df_out['quantity'].fillna('missing').astype(str)
                                    + '__' + df_out['payment'].fillna('missing').astype(str))

    # Top-50 cardinality reduction
    for col in ['funder', 'installer', 'lga']:
        if col in df_out.columns:
            vocab = TOP50.get(col, set())
            df_out[col] = (df_out[col].fillna('missing')
                           .apply(lambda x: x if x in vocab else 'other'))

    # LabelEncode remaining categoricals with the stored combined vocabulary
    for c in df_out.select_dtypes(include=['object', 'bool']).columns:
        df_out[c] = df_out[c].fillna('missing').astype(str)
        vocab = COMBINED_VOCAB.get(c)
        le = LabelEncoder()
        if vocab is not None:
            le.fit(vocab)
        else:
            le.fit(sorted(set(df_out[c].tolist() + ['missing', 'other'])))
        df_out[c] = df_out[c].apply(lambda x: x if x in le.classes_ else 'other')
        df_out[c] = le.transform(df_out[c])

    return df_out
